api_platform:
    mapping:
        paths: [ '%kernel.project_dir%/config/api_platform/resources' ]
    patch_formats:
        json: [ 'merge-patch+json' ]
    swagger:
        versions: [3]
    enable_swagger_ui: true
    enable_re_doc: true
    title: Sales Diamond API
    version: 1.0
    show_webby: false
